version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: decision-tracker-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_data:/app/uploads
      - audio_data:/app/audio
    env_file:
      - ./backend/.env
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: decision-tracker-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  backend_data:
    name: decision-tracker-uploads
  audio_data:
    name: decision-tracker-audio 